name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
